//
// Generated file, do not edit! Created by nedtool 5.6 from custom_packet.msg.
//

#ifndef __CUSTOM_PACKET_M_H
#define __CUSTOM_PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>custom_packet.msg:1</tt> by nedtool.
 * <pre>
 * packet CustomPacket
 * {
 *     int fromSource = false;
 *     int sequenceNumber;
 *     int origin;
 * }
 * </pre>
 */
class CustomPacket : public ::omnetpp::cPacket
{
  protected:
    int fromSource;
    int sequenceNumber;
    int origin;

  private:
    void copy(const CustomPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CustomPacket&);

  public:
    CustomPacket(const char *name=nullptr, short kind=0);
    CustomPacket(const CustomPacket& other);
    virtual ~CustomPacket();
    CustomPacket& operator=(const CustomPacket& other);
    virtual CustomPacket *dup() const override {return new CustomPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFromSource() const;
    virtual void setFromSource(int fromSource);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getOrigin() const;
    virtual void setOrigin(int origin);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CUSTOM_PACKET_M_H

